version: '3.8'
services:
  queue:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass <your redis password>
    volumes: 
      - queue:/data
volumes:
  queue:
    driver: local