version: '3.8'
services:
  search:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    ports:
      - '7700:7700'
    environment:
      - MEILI_MASTER_KEY='your master key'
    volumes: 
      - search:/data.ms
volumes:
  search:
    driver: local