version: '3'
services:
  neo4j:
    image: neo4j:community
    hostname: neo4j
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
    environment:
      NEO4J_AUTH: neo4j/commerce
      NEO4J_dbms_logs_debug_level: DEBUG

volumes:
  neo4j-data:
    driver: local